import Head from 'next/head'
import styles from '../styles/home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.Hero}>
          <h1>
            Hi, My Name is HUNTER!
          </h1>
        </div>
      </main>
    </div>
  )
}
